# This is a basic workflow to help you get started with Actions

name: Atom Counter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name:  CI
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/AdityaMotale/fictional-telegram.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
